# Generated by Django 4.2.5 on 2023-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('characterictics', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=0)),
            ],
        ),
    ]
